name: Compile
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:

  compile:
    name: "Compile ${{ matrix.file }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        file:
          - Examples/test_kulakarticle/instructies
          - Examples/test_kulakbeamer/IntroductieLaTeXPresentatie
          - Examples/test_kulakposter/PosterLandscape
          - Examples/test_kulakposter/PosterPortrait
          - Examples/test_kulakreport/IntroductieLaTeXHandleiding
        
    steps:

      - name: "Get .pdf"
        uses: actions/checkout@v6
        
      - name: "Compile"
        uses: xu-cheng/latex-action@v4
        with:
          work_in_root_file_dir: true
          root_file: "${{ matrix.file }}.tex"
        env:
          TEXINPUTS: ".:../../kulak/:"
  
      - name: "Upload"
        uses: actions/upload-artifact@v7
        with:
          path: "${{ matrix.file }}.pdf"
          archive: false
